### ISSUE TITLE
Unable to get plugins to work in some conditions

### ISSUE THREAD

**Issue by scribeGriff** [gionkunz/chartist-js#258]
I've been taking chartist for a spin and really like it.  And I like the idea behind the plugins, but, besides simple examples, I find situations where the plugins don't seem to work and I don't get any feedback as to why.  Here is a [fiddle](http://jsfiddle.net/scribegriff/bLu2gd1d/) where I am trying the point labels.  I also tried the missing data plugin, but it fails when chartist core sees a null value passed as a data point.  Any suggestions would be greatly appreciated.

**Comment by gionkunz** [comment]
Hi @scribeGriff I'm happy you like Chartist after giving it a spin! It looks like, at least in my Chrome, that loading the plugins directly from Github gets rejected: 

Refused to execute script from 'https://raw.githubusercontent.com/oliveraustria/chartist-plugin-missing-data/master/pluginMissingData.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
